blueprint:
  name: Different_switches_zigbee2mqtt_ULTIMATE
  description: >-
    Control any switch you want from different brands and models. 
    Version 0.95 Mod.
  domain: automation
  homeassistant:
    min_version: 2024.12.0
  input:
    input_switch:
      name: switch
      description: Switch to use (Event entity from MQTT)
      selector:
        entity:
          domain:
            - event
          integration: mqtt
          multiple: false

    # --- IKEA SECTION ---
    aan:
      name: Ikea On button
      default: []
      selector: { action: {} }
    uit:
      name: Ikea Off button
      default: []
      selector: { action: {} }
    brightness_move_up:
      name: Brightness Move Up
      default: []
      selector: { action: {} }
    brightness_move_down:
      name: Brightness Move Down
      default: []
      selector: { action: {} }
    brightness_stop:
      name: Brightness Stop
      default: []
      selector: { action: {} }
    toggle:
      name: Toggle
      default: []
      selector: { action: {} }
    brightness_up_click:
      name: Brightness Up Click
      default: []
      selector: { action: {} }
    brightness_down_click:
      name: Brightness Down Click
      default: []
      selector: { action: {} }
    brightness_up_hold:
      name: Brightness Up Hold
      default: []
      selector: { action: {} }
    brightness_up_release:
      name: Brightness Up Release
      default: []
      selector: { action: {} }
    brightness_down_hold:
      name: Brightness Down Hold
      default: []
      selector: { action: {} }
    brightness_down_release:
      name: Brightness Down Release
      default: []
      selector: { action: {} }
    toggle_hold:
      name: Toggle Hold
      default: []
      selector: { action: {} }
    arrow_left_click:
      name: Arrow Left Click
      default: []
      selector: { action: {} }
    arrow_left_hold:
      name: Arrow Left Hold
      default: []
      selector: { action: {} }
    arrow_left_release:
      name: Arrow Left Release
      default: []
      selector: { action: {} }
    arrow_right_click:
      name: Arrow Right Click
      default: []
      selector: { action: {} }
    arrow_right_hold:
      name: Arrow Right Hold
      default: []
      selector: { action: {} }
    arrow_right_release:
      name: Arrow Right Release
      default: []
      selector: { action: {} }

    # --- SINGLE/AQARA SECTION ---
    single:
      name: Single click
      default: []
      selector: { action: {} }
    double:
      name: Double click
      default: []
      selector: { action: {} }
    triple:
      name: Triple click
      default: []
      selector: { action: {} }
    quadruple:
      name: Quadruple click
      default: []
      selector: { action: {} }
    many:
      name: Many click
      default: []
      selector: { action: {} }
    hold:
      name: Hold
      default: []
      selector: { action: {} }
    long:
      name: Long press
      default: []
      selector: { action: {} }
    release:
      name: Release
      default: []
      selector: { action: {} }
    shake:
      name: Shake
      default: []
      selector: { action: {} }

    # --- AQARA 2-GANG / ROCKERS ---
    single_left:
      name: Left button single
      default: []
      selector: { action: {} }
    single_right:
      name: Right button single
      default: []
      selector: { action: {} }
    hold_left:
      name: Left button hold
      default: []
      selector: { action: {} }
    hold_right:
      name: Right button hold
      default: []
      selector: { action: {} }
    hold_both:
      name: Hold both buttons
      default: []
      selector: { action: {} }
    single_both:
      name: Single both buttons
      default: []
      selector: { action: {} }
    double_left:
      name: Double Left button
      default: []
      selector: { action: {} }
    double_right:
      name: Double Right button
      default: []
      selector: { action: {} }
    double_both:
      name: Double both buttons
      default: []
      selector: { action: {} }
    triple_both:
      name: Triple both button
      default: []
      selector: { action: {} }

    # --- AQARA 3-GANG (E1) ---
    aqara_3_left_single:
      name: 3-Gang Left Single
      default: []
      selector: { action: {} }
    aqara_3_left_double:
      name: 3-Gang Left Double
      default: []
      selector: { action: {} }
    aqara_3_center_single:
      name: 3-Gang Center Single
      default: []
      selector: { action: {} }
    aqara_3_center_double:
      name: 3-Gang Center Double
      default: []
      selector: { action: {} }
    aqara_3_right_single:
      name: 3-Gang Right Single
      default: []
      selector: { action: {} }
    aqara_3_right_double:
      name: 3-Gang Right Double
      default: []
      selector: { action: {} }
    aqara_3_left_center_single:
      name: 3-Gang Left+Center Single
      default: []
      selector: { action: {} }
    aqara_3_left_right_single:
      name: 3-Gang Left+Right Single
      default: []
      selector: { action: {} }
    aqara_3_center_right_single:
      name: 3-Gang Center+Right Single
      default: []
      selector: { action: {} }

    # --- TUYA TS0042 ---
    tuya_1_single:
      name: Tuya B1 Single
      default: []
      selector: { action: {} }
    tuya_1_double:
      name: Tuya B1 Double
      default: []
      selector: { action: {} }
    tuya_1_hold:
      name: Tuya B1 Hold
      default: []
      selector: { action: {} }
    tuya_2_single:
      name: Tuya B2 Single
      default: []
      selector: { action: {} }
    tuya_2_double:
      name: Tuya B2 Double
      default: []
      selector: { action: {} }
    tuya_2_hold:
      name: Tuya B2 Hold
      default: []
      selector: { action: {} }

    # --- HUE TAP DIAL ---
    button_1_press:
      name: Hue B1 Press
      default: []
      selector: { action: {} }
    button_1_release:
      name: Hue B1 Release
      default: []
      selector: { action: {} }
    button_1_hold:
      name: Hue B1 Hold
      default: []
      selector: { action: {} }
    button_2_press:
      name: Hue B2 Press
      default: []
      selector: { action: {} }
    button_2_release:
      name: Hue B2 Release
      default: []
      selector: { action: {} }
    button_2_hold:
      name: Hue B2 Hold
      default: []
      selector: { action: {} }
    button_3_press:
      name: Hue B3 Press
      default: []
      selector: { action: {} }
    button_3_release:
      name: Hue B3 Release
      default: []
      selector: { action: {} }
    button_3_hold:
      name: Hue B3 Hold
      default: []
      selector: { action: {} }
    button_4_press:
      name: Hue B4 Press
      default: []
      selector: { action: {} }
    button_4_release:
      name: Hue B4 Release
      default: []
      selector: { action: {} }
    button_4_hold:
      name: Hue B4 Hold
      default: []
      selector: { action: {} }
    dial_rotate_left:
      name: Hue Dial Left
      default: []
      selector: { action: {} }
    dial_rotate_right:
      name: Hue Dial Right
      default: []
      selector: { action: {} }
    dial_rotate_left_fast:
      name: Hue Dial Left Fast
      default: []
      selector: { action: {} }
    dial_rotate_right_fast:
      name: Hue Dial Right Fast
      default: []
      selector: { action: {} }

mode: parallel
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input input_switch

condition:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
  - condition: template
    value_template: "{{ trigger.to_state.attributes.event_type is defined }}"

action:
  - variables:
      command: "{{ trigger.to_state.attributes.event_type }}"
  - choose:
      # Basic IKEA / Standard
      - conditions: "{{ command == 'on' }}"
        sequence: !input aan
      - conditions: "{{ command == 'off' }}"
        sequence: !input uit
      - conditions: "{{ command == 'toggle' }}"
        sequence: !input toggle
      
      # Single/Multi click
      - conditions: "{{ command == 'single' }}"
        sequence: !input single
      - conditions: "{{ command == 'double' }}"
        sequence: !input double
      - conditions: "{{ command == 'hold' }}"
        sequence: !input hold
      - conditions: "{{ command == 'release' }}"
        sequence: !input release

      # Aqara 2-Gang logic
      - conditions: "{{ command == 'single_left' }}"
        sequence:
          - choose:
            - conditions: "{{ true }}" # Voer beide uit indien gedefinieerd
              sequence: 
                - !input single_left
                - !input aqara_3_left_single
      - conditions: "{{ command == 'single_right' }}"
        sequence:
          - choose:
            - conditions: "{{ true }}"
              sequence:
                - !input single_right
                - !input aqara_3_right_single

      # Aqara 3-Gang (Center & Combo)
      - conditions: "{{ command == 'single_center' }}"
        sequence: !input aqara_3_center_single
      - conditions: "{{ command == 'double_center' }}"
        sequence: !input aqara_3_center_double
      - conditions: "{{ command == 'single_left_center' }}"
        sequence: !input aqara_3_left_center_single
      - conditions: "{{ command == 'single_left_right' }}"
        sequence: !input aqara_3_left_right_single
      - conditions: "{{ command == 'single_center_right' }}"
        sequence: !input aqara_3_center_right_single

      # Tuya TS0042
      - conditions: "{{ command == '1_single' }}"
        sequence: !input tuya_1_single
      - conditions: "{{ command == '1_double' }}"
        sequence: !input tuya_1_double
      - conditions: "{{ command == '1_hold' }}"
        sequence: !input tuya_1_hold
      - conditions: "{{ command == '2_single' }}"
        sequence: !input tuya_2_single
      - conditions: "{{ command == '2_double' }}"
        sequence: !input tuya_2_double
      - conditions: "{{ command == '2_hold' }}"
        sequence: !input tuya_2_hold

      # Hue Tap Dial
      - conditions: "{{ command == 'button_1_press' }}"
        sequence: !input button_1_press
      - conditions: "{{ command == 'button_1_press_release' or command == 'button_1_hold_release' }}"
        sequence: !input button_1_release
      - conditions: "{{ command == 'button_1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ command in ['dial_rotate_left_step', 'dial_rotate_left_slow'] }}"
        sequence: !input dial_rotate_left
      - conditions: "{{ command in ['dial_rotate_right_step', 'dial_rotate_right_slow'] }}"
        sequence: !input dial_rotate_right
